//! Go backend: typed bindings + dispatch + mesh wrappers + scaffold over the
//! templates/go runtime (TinyGo wasip1 reactor lane).
//!
//! Type mapping (WIT → Go):
//!
//! | WIT              | Go                                                       |
//! |------------------|----------------------------------------------------------|
//! | bool             | bool                                                     |
//! | u8 u16 u32 u64   | uint8 uint16 uint32 uint64                               |
//! | s8 s16 s32 s64   | int8 int16 int32 int64                                   |
//! | f32 f64          | float32 float64                                          |
//! | char             | rune (validated unicode scalar on the wire)              |
//! | string           | string                                                   |
//! | list<T>          | []T (decode pre-allocation clamped at 4096)              |
//! | option<T>        | *T (nil = none)                                          |
//! | tuple<A, B, ..>  | anonymous struct{ F0 A; F1 B; .. }                       |
//! | record           | struct with exported Go-cased fields                     |
//! | variant          | struct{ Tag int; <Case> *T per payload case } + tag      |
//! |                  | consts + New<Variant><Case> constructors                 |
//! | enum             | type X int + consts in declaration order                 |
//! | flags            | type X uint64 + 1<<i bit consts (max 64 flags)           |
//! | result<T, E>     | value position: generic Result[T, E] (struct{} stands in |
//! |                  | for absent sides). Function-RESULT position with E =     |
//! |                  | string or absent: idiomatic Go (T, error) / error — a    |
//! |                  | non-nil error encodes as the WIRE result err case        |
//! |                  | (status stays 0); for any other E the method returns     |
//! |                  | (Result[T, E], error) and the error means status 1.      |
//!
//! Name casing: WIT kebab-case → Go by Title-casing each dash segment
//! ("echo-everything" → "EchoEverything", "a-u8" → "AU8" — no smart acronym
//! table, the per-segment Title is the whole rule). Parameters are
//! lowerCamel ("a-bool" → "aBool"); parameter names that would collide with
//! Go keywords, predeclared identifiers, or locals the generated code uses
//! get a trailing underscore.
//!
//! Declaration order: types are emitted in WIT declaration order, exports
//! before imports. Go top-level declarations are order-independent, so no
//! dependency sorting is needed (recursive references via Named just work).
//!
//! Error semantics (WIRE.md section 2): the runtime's crab_invoke maps a
//! handler error to a status-1 reply "<function>: <message>". Generated
//! handlers add "bad params: " context to decode failures and always check
//! d.Finish("params"); impl errors pass through (or become the result err
//! case, see the table above).
//!
//! Collisions: every emitted top-level identifier is checked against the
//! runtime/template identifiers and each other; a WIT name that maps onto a
//! taken Go identifier (e.g. a type named `impl` → `Impl`) fails generate()
//! with both names in the message instead of emitting broken code.

use std::collections::HashMap;
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::Path;

use anyhow::{anyhow, bail, Context, Result};

use crate::backend::Backend;
use crate::ir::{Func, Iface, Module, NamedTy, Ty};

const RUNTIME_GO: &str = include_str!("../templates/go/runtime.go");
const RUNTIME_TEST_GO: &str = include_str!("../templates/go/runtime_test.go");
const MESH_GO: &str = include_str!("../templates/go/mesh.go");
const MESH_WASM_GO: &str = include_str!("../templates/go/mesh_wasm.go");
const MESH_TEST_GO: &str = include_str!("../templates/go/mesh_test.go");

const GENERATED_HEADER: &str = "// Code generated by crabgen. DO NOT EDIT.";

/// Top-level identifiers already declared by the template files (package gen
/// is one package: runtime.go + mesh.go + runtime_test.go + mesh_test.go +
/// schema.go), plus the fixed names bindings.go itself declares.
const RESERVED: &[&str] = &[
    // runtime.go
    "EncodeUleb",
    "EncodeSleb",
    "EncodeBool",
    "EncodeU8",
    "EncodeU16",
    "EncodeU32",
    "EncodeU64",
    "EncodeS8",
    "EncodeS16",
    "EncodeS32",
    "EncodeS64",
    "EncodeF32",
    "EncodeF64",
    "EncodeChar",
    "EncodeString",
    "EncodeListLen",
    "EncodeCase",
    "EncodeOptionTag",
    "EncodeResultTag",
    "EncodeFlags",
    "errEOF",
    "errUlebOver",
    "errUlebLong",
    "errSlebOver",
    "errSlebLong",
    "errBadUTF8",
    "errFlagsUnused",
    "Decoder",
    "NewDecoder",
    "Schema",
    "handlers",
    "allocs",
    "reply",
    "lenbuf",
    "replyOK",
    "replyErr",
    "crabAlloc",
    "crabSchema",
    "crabInvoke",
    // mesh.go / mesh_wasm.go
    "meshHostCall",
    "slicePtr",
    "readLenbuf",
    "MeshCall",
    "parseMeshReply",
    "crabcraftCall",
    // runtime_test.go (same package: test-only identifiers still collide)
    "vector",
    "tdesc",
    "dOption",
    "dResult",
    "dVariant",
    "numLit",
    "jsonString",
    "isNull",
    "isScalarKind",
    "mustHex",
    "encodeJSON",
    "decodeValue",
    "reencodeValue",
    "expectScalar",
    "loadVectors",
    "TestWireVectors",
    "TestStrictBytes",
    "TestTrailingBytes",
    "TestUlebOverflowBits",
    "TestSlebSignExtension",
    "TestCharValidation",
    "TestFlagsValidation",
    "TestVariantEnumRange",
    "TestResultNoPayloadTypes",
    "TestEOFEverywhere",
    "TestEmptyValues",
    "TestParseMeshReply",
    // schema.go
    "schemaJSON",
    // bindings.go fixed declarations
    "Impl",
    "SetImpl",
    "impl",
    "errNoImpl",
    "Result",
];

/// Go keywords + predeclared identifiers + locals the generated code uses;
/// parameter names landing here get a trailing underscore.
const PARAM_AVOID: &[&str] = &[
    // keywords
    "break",
    "case",
    "chan",
    "const",
    "continue",
    "default",
    "defer",
    "else",
    "fallthrough",
    "for",
    "func",
    "go",
    "goto",
    "if",
    "import",
    "interface",
    "map",
    "package",
    "range",
    "return",
    "select",
    "struct",
    "switch",
    "type",
    "var",
    // predeclared
    "any",
    "append",
    "bool",
    "byte",
    "cap",
    "clear",
    "close",
    "comparable",
    "complex",
    "complex64",
    "complex128",
    "copy",
    "delete",
    "error",
    "false",
    "float32",
    "float64",
    "imag",
    "int",
    "int8",
    "int16",
    "int32",
    "int64",
    "iota",
    "len",
    "make",
    "max",
    "min",
    "new",
    "nil",
    "panic",
    "print",
    "println",
    "real",
    "recover",
    "rune",
    "string",
    "true",
    "uint",
    "uint8",
    "uint16",
    "uint32",
    "uint64",
    "uintptr",
    // ONLY the generated locals that share a scope with WIT params (args
    // decoders, handlers, mesh wrappers). Codec-helper locals (v, c, bits,
    // i, n, set, payload...) live in functions with fixed signatures and
    // never see a param, so they are deliberately NOT listed here.
    "d",
    "err",
    "out",
    "r",
    "body",
    "workload",
    "msg",
    "impl",
    "isErr",
];

pub struct GoBackend;

impl Backend for GoBackend {
    fn lang(&self) -> &'static str {
        "go"
    }

    fn impl_ext(&self) -> &'static str {
        "go"
    }

    fn generate(&self, m: &Module, dir: &Path) -> Result<()> {
        let g = Gen::new(m, &project_name(dir)?)?;
        let gen_dir = dir.join("gen");
        let write = |name: &str, content: &str| -> Result<()> {
            let path = gen_dir.join(name);
            fs::write(&path, content).with_context(|| format!("writing {}", path.display()))
        };
        write("runtime.go", RUNTIME_GO)?;
        write("runtime_test.go", RUNTIME_TEST_GO)?;
        write("schema.go", &schema_go())?;
        write("bindings.go", &g.bindings_go()?)?;
        if !m.imports.is_empty() {
            write("mesh.go", MESH_GO)?;
            write("mesh_wasm.go", MESH_WASM_GO)?;
            write("mesh_test.go", MESH_TEST_GO)?;
            write("imports.go", &g.imports_go()?)?;
        }
        // README quotes WIT-derived content (the export instance), so it is
        // regenerated alongside gen/ — the canonical flow swaps the starter
        // WIT and regens, which must not leave stale docs. It lives at the
        // project root, not gen/.
        let readme_path = dir.join("README.md");
        fs::write(&readme_path, readme(&project_name(dir)?, m))
            .with_context(|| format!("writing {}", readme_path.display()))?;
        Ok(())
    }

    fn scaffold(&self, m: &Module, dir: &Path) -> Result<()> {
        let name = project_name(dir)?;
        let g = Gen::new(m, &name)?;
        let write_once = |path: &Path, content: &str| -> Result<()> {
            if !path.exists() {
                fs::write(path, content).with_context(|| format!("writing {}", path.display()))?;
            }
            Ok(())
        };
        write_once(&dir.join("impl.go"), &g.impl_go()?)?;
        write_once(&dir.join("go.mod"), &go_mod(&name))?;
        let build = dir.join("build.sh");
        if !build.exists() {
            fs::write(&build, build_sh(&name))?;
            let mut perms = fs::metadata(&build)?.permissions();
            perms.set_mode(0o755);
            fs::set_permissions(&build, perms)?;
        }
        Ok(())
    }

    fn missing_impls(&self, m: &Module, dir: &Path) -> Result<Vec<String>> {
        let g = Gen::new(m, &project_name(dir)?)?;
        let src = fs::read_to_string(dir.join("impl.go")).unwrap_or_default();
        let mut missing = Vec::new();
        for iface in &m.exports {
            for f in &iface.funcs {
                let go_name = go_pascal(&f.wit_name);
                if !src.contains(&format!(") {go_name}(")) {
                    missing.push(format!("func (App) {}", g.method_sig(f, "gen.")?));
                }
            }
        }
        Ok(missing)
    }
}

fn project_name(dir: &Path) -> Result<String> {
    dir.file_name()
        .map(|n| n.to_string_lossy().to_string())
        .ok_or_else(|| anyhow!("project dir {} has no name", dir.display()))
}

// ---------------------------------------------------------------------------
// naming
// ---------------------------------------------------------------------------

/// kebab-case → PascalCase: Title each dash segment ("a-u8" → "AU8").
fn go_pascal(kebab: &str) -> String {
    kebab
        .split('-')
        .map(|seg| {
            let mut c = seg.chars();
            match c.next() {
                Some(f) => f.to_ascii_uppercase().to_string() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

/// kebab-case → lowerCamel parameter name, underscore-mangled away from Go
/// keywords/predeclared names/generated locals and temp-name patterns.
fn go_param(kebab: &str) -> String {
    let mut segs = kebab.split('-');
    let mut s = segs.next().unwrap_or_default().to_string();
    for seg in segs {
        s.push_str(&go_pascal(seg));
    }
    if PARAM_AVOID.contains(&s.as_str()) || is_temp_shaped(&s) {
        s.push('_');
    }
    s
}

/// Matches the generated temp-name pattern (x0, n1, i2, ok0, isErr0...).
fn is_temp_shaped(s: &str) -> bool {
    for prefix in ["x", "n", "i", "ok", "isErr"] {
        if let Some(rest) = s.strip_prefix(prefix) {
            if !rest.is_empty() && rest.bytes().all(|b| b.is_ascii_digit()) {
                return true;
            }
        }
    }
    false
}

// ---------------------------------------------------------------------------
// emission plumbing
// ---------------------------------------------------------------------------

/// Line writer with tab indentation (gofmt's). `line` may carry embedded
/// newlines (multiline anonymous struct types render their own inner tabs).
struct W {
    buf: String,
    ind: usize,
}

impl W {
    fn new() -> Self {
        W {
            buf: String::new(),
            ind: 0,
        }
    }

    fn line(&mut self, s: impl AsRef<str>) {
        let s = s.as_ref();
        if !s.is_empty() {
            for _ in 0..self.ind {
                self.buf.push('\t');
            }
            self.buf.push_str(s);
        }
        self.buf.push('\n');
    }

    fn open(&mut self, s: impl AsRef<str>) {
        self.line(s);
        self.ind += 1;
    }

    fn close(&mut self, s: impl AsRef<str>) {
        self.ind -= 1;
        self.line(s);
    }
}

/// Per-function emission state: fresh temp names, the error-return statement
/// for the current context, and whether an `err` assignment was emitted (so
/// encode helpers know to declare `var err error`).
struct Cx {
    tmp: usize,
    ret: &'static str,
    used_err: bool,
}

impl Cx {
    fn new(ret: &'static str) -> Self {
        Cx {
            tmp: 0,
            ret,
            used_err: false,
        }
    }

    fn fresh(&mut self, base: &str) -> String {
        let n = self.tmp;
        self.tmp += 1;
        format!("{base}{n}")
    }
}

/// gofmt's struct-field alignment: within a section, names are space-padded
/// to the longest name + 1; a field whose type spans multiple lines is the
/// LAST member of its section (verified against gofmt empirically).
fn align_fields(fields: &[(String, String)], ind: usize) -> String {
    let tab = "\t".repeat(ind);
    let mut out = String::new();
    let mut i = 0;
    while i < fields.len() {
        let mut j = i;
        while j < fields.len() && !fields[j].1.contains('\n') {
            j += 1;
        }
        let end = (j + 1).min(fields.len());
        let maxn = fields[i..end].iter().map(|(n, _)| n.len()).max().unwrap();
        for (name, ty) in &fields[i..end] {
            let pad = " ".repeat(maxn - name.len());
            out.push_str(&format!("{tab}{name}{pad} {ty}\n"));
        }
        i = end;
    }
    out
}

/// Scalar types: (Encode* function, Decoder method, Go type).
fn scalar(ty: &Ty) -> Option<(&'static str, &'static str, &'static str)> {
    Some(match ty {
        Ty::Bool => ("EncodeBool", "Bool", "bool"),
        Ty::U8 => ("EncodeU8", "U8", "uint8"),
        Ty::U16 => ("EncodeU16", "U16", "uint16"),
        Ty::U32 => ("EncodeU32", "U32", "uint32"),
        Ty::U64 => ("EncodeU64", "U64", "uint64"),
        Ty::S8 => ("EncodeS8", "S8", "int8"),
        Ty::S16 => ("EncodeS16", "S16", "int16"),
        Ty::S32 => ("EncodeS32", "S32", "int32"),
        Ty::S64 => ("EncodeS64", "S64", "int64"),
        Ty::F32 => ("EncodeF32", "F32", "float32"),
        Ty::F64 => ("EncodeF64", "F64", "float64"),
        Ty::Char => ("EncodeChar", "Char", "rune"),
        Ty::String => ("EncodeString", "String", "string"),
        _ => return None,
    })
}

/// A type that encodes to zero bytes (empty tuple): encode emits no
/// statements for it, so deref temps must not be created.
fn is_unit(ty: &Ty) -> bool {
    matches!(ty, Ty::Tuple(ts) if ts.is_empty())
}

/// Go type expression for a value-position type. `qual` is "" inside
/// package gen, "gen." in impl.go signatures. `ind` is the indent level
/// of the line the type starts on (anonymous tuple structs span lines).
fn go_ty(ty: &Ty, qual: &str, ind: usize) -> Result<String> {
    Ok(match ty {
        Ty::List(t) => format!("[]{}", go_ty(t, qual, ind)?),
        Ty::Option(t) => format!("*{}", go_ty(t, qual, ind)?),
        Ty::Tuple(ts) => {
            if ts.is_empty() {
                "struct{}".to_string()
            } else {
                let fields = ts
                    .iter()
                    .enumerate()
                    .map(|(i, t)| Ok((format!("F{i}"), go_ty(t, qual, ind + 1)?)))
                    .collect::<Result<Vec<_>>>()?;
                format!(
                    "struct {{\n{}{}}}",
                    align_fields(&fields, ind + 1),
                    "\t".repeat(ind)
                )
            }
        }
        Ty::Result(ok, errt) => {
            let side = |t: &Option<Box<Ty>>| -> Result<String> {
                Ok(match t {
                    Some(t) => go_ty(t, qual, ind)?,
                    None => "struct{}".to_string(),
                })
            };
            format!("{qual}Result[{}, {}]", side(ok)?, side(errt)?)
        }
        Ty::Named(n) => format!("{qual}{}", go_pascal(n)),
        Ty::Record(_) | Ty::Variant(_) | Ty::Enum(_) | Ty::Flags(_) => {
            bail!("internal error: anonymous {ty:?} cannot appear in value position (WIT names these)")
        }
        _ => scalar(ty)
            .map(|(_, _, go)| go.to_string())
            .ok_or_else(|| anyhow!("unmapped type {ty:?}"))?,
    })
}

/// How a function's WIT result maps onto its Go signature.
enum Ret<'a> {
    /// no WIT result → `error` (non-nil = status-1 reply)
    None,
    /// plain value → `(T, error)` (non-nil = status-1 reply)
    Plain(&'a Ty),
    /// result<T, string> / result<T> / result<_,_> → `(T, error)` / `error`;
    /// a non-nil error is the WIRE result ERR CASE (status stays 0).
    /// `has_msg` = the err side carries the string payload.
    ResStr { ok: Option<&'a Ty>, has_msg: bool },
    /// result with any other err type → `(Result[T, E], error)`
    /// (non-nil error = status-1 reply)
    ResTyped(&'a Ty),
}

impl<'a> Ret<'a> {
    /// The Go value type returned ahead of `error`, if any.
    fn value_ty(&self) -> Option<&'a Ty> {
        match self {
            Ret::None => None,
            Ret::Plain(t) => Some(t),
            Ret::ResStr { ok, .. } => *ok,
            Ret::ResTyped(t) => Some(t),
        }
    }
}

// -- encode / decode statement emission -----------------------------------

/// Statements appending the WIRE encoding of `expr` (type `ty`) to `out`.
fn emit_encode(w: &mut W, cx: &mut Cx, ty: &Ty, expr: &str) -> Result<()> {
    match ty {
        Ty::List(t) => {
            w.line(format!("out = EncodeListLen(out, len({expr}))"));
            let x = cx.fresh("x");
            w.open(format!("for _, {x} := range {expr} {{"));
            emit_encode(w, cx, t, &x)?;
            w.close("}");
        }
        Ty::Option(t) => {
            w.line(format!("out = EncodeOptionTag(out, {expr} != nil)"));
            w.open(format!("if {expr} != nil {{"));
            emit_encode_deref(w, cx, t, expr)?;
            w.close("}");
        }
        Ty::Tuple(ts) => {
            for (i, t) in ts.iter().enumerate() {
                emit_encode(w, cx, t, &format!("{expr}.F{i}"))?;
            }
        }
        Ty::Result(ok, errt) => {
            w.line(format!("out = EncodeResultTag(out, {expr}.IsErr)"));
            match (ok.as_deref(), errt.as_deref()) {
                (Some(okt), Some(et)) => {
                    w.open(format!("if {expr}.IsErr {{"));
                    emit_encode(w, cx, et, &format!("{expr}.Err"))?;
                    w.close("} else {");
                    w.ind += 1;
                    emit_encode(w, cx, okt, &format!("{expr}.Ok"))?;
                    w.close("}");
                }
                (None, Some(et)) => {
                    w.open(format!("if {expr}.IsErr {{"));
                    emit_encode(w, cx, et, &format!("{expr}.Err"))?;
                    w.close("}");
                }
                (Some(okt), None) => {
                    w.open(format!("if !{expr}.IsErr {{"));
                    emit_encode(w, cx, okt, &format!("{expr}.Ok"))?;
                    w.close("}");
                }
                (None, None) => {}
            }
        }
        Ty::Named(n) => {
            cx.used_err = true;
            w.line(format!("out, err = encode{}(out, {expr})", go_pascal(n)));
            w.open("if err != nil {");
            w.line(cx.ret);
            w.close("}");
        }
        Ty::Record(_) | Ty::Variant(_) | Ty::Enum(_) | Ty::Flags(_) => {
            bail!("internal error: anonymous {ty:?} in encode position")
        }
        _ => {
            let (enc, _, _) = scalar(ty).ok_or_else(|| anyhow!("unmapped type {ty:?}"))?;
            w.line(format!("out = {enc}(out, {expr})"));
        }
    }
    Ok(())
}

/// Encode `*ptr` of type `ty`: copies into a temp first so member access
/// stays unambiguous (`*p.F0` would parse as `*(p.F0)`).
fn emit_encode_deref(w: &mut W, cx: &mut Cx, ty: &Ty, ptr: &str) -> Result<()> {
    if is_unit(ty) {
        return Ok(()); // zero bytes on the wire, nothing to reference
    }
    let x = cx.fresh("x");
    w.line(format!("{x} := *{ptr}"));
    emit_encode(w, cx, ty, &x)
}

/// Statements decoding a value of `ty` from `d` into lvalue `dest`.
/// Every surrounding function uses named results, so the error path is a
/// plain `return`.
fn emit_decode(w: &mut W, cx: &mut Cx, ty: &Ty, dest: &str) -> Result<()> {
    let errcheck = |w: &mut W| {
        w.open("if err != nil {");
        w.line("return");
        w.close("}");
    };
    match ty {
        Ty::List(t) => {
            let n = cx.fresh("n");
            w.line(format!("var {n} int"));
            w.line(format!("{n}, err = d.ListLen()"));
            errcheck(w);
            // the count is attacker-controlled: clamp pre-allocation
            // (crab-sdk caps initial capacity at 4096) and append
            w.line(format!(
                "{dest} = make({}, 0, min({n}, 4096))",
                go_ty(ty, "", w.ind)?
            ));
            let i = cx.fresh("i");
            w.open(format!("for {i} := 0; {i} < {n}; {i}++ {{"));
            let x = cx.fresh("x");
            w.line(format!("var {x} {}", go_ty(t, "", w.ind)?));
            emit_decode(w, cx, t, &x)?;
            w.line(format!("{dest} = append({dest}, {x})"));
            w.close("}");
        }
        Ty::Option(t) => {
            let ok = cx.fresh("ok");
            w.line(format!("var {ok} bool"));
            w.line(format!("{ok}, err = d.OptionTag()"));
            errcheck(w);
            w.open(format!("if {ok} {{"));
            let x = cx.fresh("x");
            w.line(format!("var {x} {}", go_ty(t, "", w.ind)?));
            emit_decode(w, cx, t, &x)?;
            w.line(format!("{dest} = &{x}"));
            w.close("}");
        }
        Ty::Tuple(ts) => {
            for (i, t) in ts.iter().enumerate() {
                emit_decode(w, cx, t, &format!("{dest}.F{i}"))?;
            }
        }
        Ty::Result(ok, errt) => {
            let tag = cx.fresh("isErr");
            w.line(format!("var {tag} bool"));
            w.line(format!("{tag}, err = d.ResultTag()"));
            errcheck(w);
            w.line(format!("{dest}.IsErr = {tag}"));
            match (ok.as_deref(), errt.as_deref()) {
                (Some(okt), Some(et)) => {
                    w.open(format!("if {tag} {{"));
                    emit_decode(w, cx, et, &format!("{dest}.Err"))?;
                    w.close("} else {");
                    w.ind += 1;
                    emit_decode(w, cx, okt, &format!("{dest}.Ok"))?;
                    w.close("}");
                }
                (None, Some(et)) => {
                    w.open(format!("if {tag} {{"));
                    emit_decode(w, cx, et, &format!("{dest}.Err"))?;
                    w.close("}");
                }
                (Some(okt), None) => {
                    w.open(format!("if !{tag} {{"));
                    emit_decode(w, cx, okt, &format!("{dest}.Ok"))?;
                    w.close("}");
                }
                (None, None) => {}
            }
        }
        Ty::Named(n) => {
            w.line(format!("{dest}, err = decode{}(d)", go_pascal(n)));
            errcheck(w);
        }
        Ty::Record(_) | Ty::Variant(_) | Ty::Enum(_) | Ty::Flags(_) => {
            bail!("internal error: anonymous {ty:?} in decode position")
        }
        _ => {
            let (_, dec, _) = scalar(ty).ok_or_else(|| anyhow!("unmapped type {ty:?}"))?;
            w.line(format!("{dest}, err = d.{dec}()"));
            errcheck(w);
        }
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// the generator
// ---------------------------------------------------------------------------

struct Gen<'a> {
    m: &'a Module,
    project: String,
    /// WIT type name → definition, across every interface (one Go package).
    types: HashMap<&'a str, &'a Ty>,
    /// whether the generic Result[T, E] declaration is needed
    need_result: bool,
}

impl<'a> Gen<'a> {
    fn new(m: &'a Module, project: &str) -> Result<Self> {
        let mut g = Gen {
            m,
            project: project.to_string(),
            types: HashMap::new(),
            need_result: false,
        };
        for iface in m.exports.iter().chain(&m.imports) {
            for t in &iface.types {
                if g.types.insert(t.wit_name.as_str(), &t.ty).is_some() {
                    bail!(
                        "type `{}` is declared in more than one interface; the Go lane puts \
                         every type in one package — rename one of them",
                        t.wit_name
                    );
                }
            }
        }
        g.validate()?;
        g.need_result = g.scan_need_result()?;
        Ok(g)
    }

    /// Claim every top-level Go identifier this module will emit; duplicate
    /// or reserved names fail loudly here, before anything is written.
    fn validate(&self) -> Result<()> {
        let mut taken: HashMap<String, String> = RESERVED
            .iter()
            .map(|s| (s.to_string(), "the gen runtime/bindings".to_string()))
            .collect();
        let mut claim = |ident: String, what: String| -> Result<()> {
            if let Some(owner) = taken.get(&ident) {
                bail!("{what} maps to Go identifier `{ident}`, which collides with {owner}; rename it in the WIT");
            }
            taken.insert(ident, what);
            Ok(())
        };

        for iface in self.m.exports.iter().chain(&self.m.imports) {
            for t in &iface.types {
                let p = go_pascal(&t.wit_name);
                let what = format!("WIT type `{}` ({})", t.wit_name, iface.instance);
                claim(p.clone(), what.clone())?;
                claim(format!("encode{p}"), what.clone())?;
                claim(format!("decode{p}"), what.clone())?;
                match &t.ty {
                    // struct fields are their own (per-type) identifier scope
                    Ty::Record(fields) => {
                        let mut seen: HashMap<String, &str> = HashMap::new();
                        for (fname, _) in fields {
                            let fp = go_pascal(fname);
                            if let Some(prev) = seen.insert(fp.clone(), fname) {
                                bail!(
                                    "{what}: fields `{prev}` and `{fname}` both map to Go field `{fp}`; rename one in the WIT"
                                );
                            }
                        }
                    }
                    Ty::Enum(cases) => {
                        for c in cases {
                            claim(format!("{p}{}", go_pascal(c)), format!("{what} case `{c}`"))?;
                        }
                    }
                    Ty::Flags(flags) => {
                        if flags.len() > 64 {
                            bail!(
                                "flags `{}` has {} flags; the Go lane (type {p} uint64) supports at most 64",
                                t.wit_name,
                                flags.len()
                            );
                        }
                        for f in flags {
                            claim(format!("{p}{}", go_pascal(f)), format!("{what} flag `{f}`"))?;
                        }
                    }
                    Ty::Variant(cases) => {
                        // payload cases become struct fields next to the
                        // generated Tag discriminant: that struct is its own
                        // identifier scope, with Tag pre-reserved
                        let mut fields: HashMap<String, String> = HashMap::new();
                        fields.insert(
                            "Tag".to_string(),
                            "the generated Tag discriminant".to_string(),
                        );
                        for (c, payload) in cases {
                            let cp = go_pascal(c);
                            claim(format!("{p}Tag{cp}"), format!("{what} case `{c}`"))?;
                            claim(format!("New{p}{cp}"), format!("{what} case `{c}`"))?;
                            if payload.is_some() {
                                if let Some(prev) =
                                    fields.insert(cp.clone(), format!("payload case `{c}`"))
                                {
                                    bail!(
                                        "{what}: payload case `{c}` maps to Go field `{cp}`, which collides with {prev}; rename it in the WIT"
                                    );
                                }
                            }
                        }
                    }
                    _ => {}
                }
            }
        }
        for iface in &self.m.exports {
            let mut methods: HashMap<String, String> = HashMap::new();
            for f in &iface.funcs {
                let p = go_pascal(&f.wit_name);
                let what = format!("WIT function `{}` ({})", f.wit_name, iface.instance);
                claim(format!("handle{p}"), what.clone())?;
                claim(format!("decode{p}Args"), what.clone())?;
                if let Some(prev) = methods.insert(p.clone(), f.wit_name.clone()) {
                    bail!(
                        "WIT functions `{prev}` and `{}` both map to Go method `{p}`; rename one",
                        f.wit_name
                    );
                }
                self.validate_params(f, &what)?;
            }
        }
        for iface in &self.m.imports {
            let ip = go_pascal(iface_short(&iface.instance));
            for f in &iface.funcs {
                let what = format!("WIT import `{}` ({})", f.wit_name, iface.instance);
                claim(format!("{ip}{}", go_pascal(&f.wit_name)), what.clone())?;
                self.validate_params(f, &what)?;
            }
        }
        Ok(())
    }

    fn validate_params(&self, f: &Func, what: &str) -> Result<()> {
        let mut seen: HashMap<String, &str> = HashMap::new();
        for (name, _) in &f.params {
            if let Some(prev) = seen.insert(go_param(name), name) {
                bail!("{what}: params `{prev}` and `{name}` both map to the same Go name");
            }
        }
        Ok(())
    }

    /// Follow Named references to the defining type (alias chains too).
    fn resolve(&self, ty: &'a Ty) -> Result<&'a Ty> {
        let mut t = ty;
        for _ in 0..64 {
            match t {
                Ty::Named(n) => {
                    t = self
                        .types
                        .get(n.as_str())
                        .copied()
                        .ok_or_else(|| anyhow!("unresolved type reference `{n}`"))?;
                }
                _ => return Ok(t),
            }
        }
        bail!("type alias cycle while resolving `{ty:?}`");
    }

    fn classify(&self, f: &'a Func) -> Result<Ret<'a>> {
        let Some(rty) = &f.result else {
            return Ok(Ret::None);
        };
        if let Ty::Result(ok, errt) = self.resolve(rty)? {
            let ok = ok.as_deref();
            match errt.as_deref() {
                None => return Ok(Ret::ResStr { ok, has_msg: false }),
                Some(e) if matches!(self.resolve(e)?, Ty::String) => {
                    return Ok(Ret::ResStr { ok, has_msg: true });
                }
                Some(_) => return Ok(Ret::ResTyped(rty)),
            }
        }
        Ok(Ret::Plain(rty))
    }

    /// True if any value position needs the generic Result[T, E] type (a
    /// result NOT mapped to (T, error) at a function boundary).
    fn scan_need_result(&self) -> Result<bool> {
        fn walk(ty: &Ty) -> bool {
            match ty {
                Ty::Result(..) => true,
                Ty::List(t) | Ty::Option(t) => walk(t),
                Ty::Tuple(ts) => ts.iter().any(walk),
                Ty::Record(fs) => fs.iter().any(|(_, t)| walk(t)),
                Ty::Variant(cs) => cs.iter().any(|(_, t)| t.as_ref().is_some_and(walk)),
                _ => false,
            }
        }
        for iface in self.m.exports.iter().chain(&self.m.imports) {
            for t in &iface.types {
                if walk(&t.ty) {
                    return Ok(true);
                }
            }
            for f in &iface.funcs {
                if f.params.iter().any(|(_, t)| walk(t)) {
                    return Ok(true);
                }
                let needed = match self.classify(f)? {
                    Ret::None => false,
                    Ret::Plain(t) => walk(t),
                    Ret::ResStr { ok, .. } => ok.is_some_and(walk),
                    Ret::ResTyped(_) => true,
                };
                if needed {
                    return Ok(true);
                }
            }
        }
        Ok(false)
    }

    /// Go zero-value expression for a type (used by the scaffolded stubs).
    fn zero(&self, ty: &Ty, qual: &str, ind: usize) -> Result<String> {
        Ok(match ty {
            Ty::Bool => "false".to_string(),
            Ty::String => "\"\"".to_string(),
            Ty::List(_) | Ty::Option(_) => "nil".to_string(),
            Ty::Tuple(_) | Ty::Result(..) => format!("{}{{}}", go_ty(ty, qual, ind)?),
            Ty::Named(n) => match self.resolve(ty)? {
                Ty::Record(_) | Ty::Variant(_) => format!("{qual}{}{{}}", go_pascal(n)),
                Ty::Enum(_) | Ty::Flags(_) => "0".to_string(),
                under => self.zero(under, qual, ind)?,
            },
            _ => "0".to_string(), // ints, floats, char
        })
    }

    // -- named type declarations + codec helpers ------------------------------

    fn emit_named_ty(&self, w: &mut W, iface: &Iface, t: &NamedTy) -> Result<()> {
        let p = go_pascal(&t.wit_name);
        match &t.ty {
            Ty::Record(fields) => {
                w.line(format!(
                    "// {p} mirrors the WIT record `{}` ({}).",
                    t.wit_name, iface.instance
                ));
                let fs = fields
                    .iter()
                    .map(|(n, ft)| Ok((go_pascal(n), go_ty(ft, "", 1)?)))
                    .collect::<Result<Vec<_>>>()?;
                w.line(format!("type {p} struct {{"));
                w.buf.push_str(&align_fields(&fs, 1));
                w.line("}");
                w.line("");
                self.emit_record_codecs(w, &p, fields)?;
            }
            Ty::Variant(cases) => self.emit_variant(w, iface, t, cases)?,
            Ty::Enum(cases) => self.emit_enum(w, iface, t, cases),
            Ty::Flags(flags) => self.emit_flags(w, iface, t, flags),
            other => {
                // alias: identical Go type, helpers delegate to the structure
                w.line(format!(
                    "// {p} aliases the WIT type `{}` ({}).",
                    t.wit_name, iface.instance
                ));
                w.line(format!("type {p} = {}", go_ty(other, "", 0)?));
                w.line("");
                let body = self.encode_helper_body(other, "v")?;
                self.write_encode_helper(w, &p, body);
                let mut cx = Cx::new("return");
                let mut bw = W::new();
                bw.ind = 1;
                emit_decode(&mut bw, &mut cx, other, "v")?;
                self.write_decode_helper(w, &p, &bw.buf);
            }
        }
        Ok(())
    }

    fn emit_record_codecs(&self, w: &mut W, p: &str, fields: &[(String, Ty)]) -> Result<()> {
        let mut cx = Cx::new("return nil, err");
        let mut bw = W::new();
        bw.ind = 1;
        for (n, ft) in fields {
            emit_encode(&mut bw, &mut cx, ft, &format!("v.{}", go_pascal(n)))?;
        }
        let mut body = bw.buf;
        if cx.used_err {
            body = format!("\tvar err error\n{body}");
        }
        self.write_encode_helper(w, p, body);

        let mut cx = Cx::new("return");
        let mut bw = W::new();
        bw.ind = 1;
        for (n, ft) in fields {
            emit_decode(&mut bw, &mut cx, ft, &format!("v.{}", go_pascal(n)))?;
        }
        self.write_decode_helper(w, p, &bw.buf);
        Ok(())
    }

    fn write_encode_helper(&self, w: &mut W, p: &str, body: String) {
        w.line(format!(
            "func encode{p}(out []byte, v {p}) ([]byte, error) {{"
        ));
        w.buf.push_str(&body);
        w.line("\treturn out, nil");
        w.line("}");
        w.line("");
    }

    fn write_decode_helper(&self, w: &mut W, p: &str, body: &str) {
        w.line(format!("func decode{p}(d *Decoder) (v {p}, err error) {{"));
        w.buf.push_str(body);
        w.line("\treturn");
        w.line("}");
        w.line("");
    }

    /// Encode-helper body for an alias underlying type (expr is `v`).
    fn encode_helper_body(&self, ty: &Ty, expr: &str) -> Result<String> {
        let mut cx = Cx::new("return nil, err");
        let mut bw = W::new();
        bw.ind = 1;
        emit_encode(&mut bw, &mut cx, ty, expr)?;
        let mut body = bw.buf;
        if cx.used_err {
            body = format!("\tvar err error\n{body}");
        }
        Ok(body)
    }

    fn emit_enum(&self, w: &mut W, iface: &Iface, t: &NamedTy, cases: &[String]) {
        let p = go_pascal(&t.wit_name);
        w.line(format!(
            "// {p} mirrors the WIT enum `{}` ({}); consts in declaration order.",
            t.wit_name, iface.instance
        ));
        w.line(format!("type {p} int"));
        w.line("");
        w.line("const (");
        for (i, c) in cases.iter().enumerate() {
            if i == 0 {
                w.line(format!("\t{p}{} {p} = iota", go_pascal(c)));
            } else {
                w.line(format!("\t{p}{}", go_pascal(c)));
            }
        }
        w.line(")");
        w.line("");
        let n = cases.len();
        w.open(format!(
            "func encode{p}(out []byte, v {p}) ([]byte, error) {{"
        ));
        w.open(format!("if v < 0 || v >= {n} {{"));
        w.line(format!(
            "return nil, fmt.Errorf(\"invalid {p}: %d\", int(v))"
        ));
        w.close("}");
        w.line("return EncodeCase(out, uint32(v)), nil");
        w.close("}");
        w.line("");
        w.open(format!("func decode{p}(d *Decoder) ({p}, error) {{"));
        w.line(format!("c, err := d.EnumCase({n})"));
        w.line(format!("return {p}(c), err"));
        w.close("}");
        w.line("");
    }

    fn emit_flags(&self, w: &mut W, iface: &Iface, t: &NamedTy, flags: &[String]) {
        let p = go_pascal(&t.wit_name);
        w.line(format!(
            "// {p} mirrors the WIT flags `{}` ({}); bit i = flag i.",
            t.wit_name, iface.instance
        ));
        w.line(format!("type {p} uint64"));
        w.line("");
        w.line("const (");
        for (i, f) in flags.iter().enumerate() {
            if i == 0 {
                w.line(format!("\t{p}{} {p} = 1 << iota", go_pascal(f)));
            } else {
                w.line(format!("\t{p}{}", go_pascal(f)));
            }
        }
        w.line(")");
        w.line("");
        let n = flags.len();
        w.open(format!(
            "func encode{p}(out []byte, v {p}) ([]byte, error) {{"
        ));
        w.open(format!("if v>>{n} != 0 {{"));
        w.line(format!(
            "return nil, fmt.Errorf(\"invalid {p}: unknown bits in %#x\", uint64(v))"
        ));
        w.close("}");
        w.line(format!("bits := make([]bool, {n})"));
        w.open("for i := range bits {");
        w.line("bits[i] = v&(1<<i) != 0");
        w.close("}");
        w.line("return EncodeFlags(out, bits), nil");
        w.close("}");
        w.line("");
        w.open(format!("func decode{p}(d *Decoder) ({p}, error) {{"));
        w.line(format!("bits, err := d.Flags({n})"));
        w.open("if err != nil {");
        w.line("return 0, err");
        w.close("}");
        w.line(format!("var v {p}"));
        w.open("for i, set := range bits {");
        w.open("if set {");
        w.line("v |= 1 << i");
        w.close("}");
        w.close("}");
        w.line("return v, nil");
        w.close("}");
        w.line("");
    }

    fn emit_variant(
        &self,
        w: &mut W,
        iface: &Iface,
        t: &NamedTy,
        cases: &[(String, Option<Ty>)],
    ) -> Result<()> {
        let p = go_pascal(&t.wit_name);
        w.line(format!(
            "// {p} mirrors the WIT variant `{}` ({}): Tag selects the case",
            t.wit_name, iface.instance
        ));
        w.line(format!(
            "// ({p}Tag* consts, declaration order); for a payload case exactly the"
        ));
        w.line(format!(
            "// matching pointer field must be non-nil. Prefer the New{p}* constructors."
        ));
        let mut fields = vec![("Tag".to_string(), "int".to_string())];
        for (c, payload) in cases {
            if let Some(pt) = payload {
                fields.push((go_pascal(c), format!("*{}", go_ty(pt, "", 1)?)));
            }
        }
        w.line(format!("type {p} struct {{"));
        w.buf.push_str(&align_fields(&fields, 1));
        w.line("}");
        w.line("");
        w.line("const (");
        for (i, (c, _)) in cases.iter().enumerate() {
            if i == 0 {
                w.line(format!("\t{p}Tag{} = iota", go_pascal(c)));
            } else {
                w.line(format!("\t{p}Tag{}", go_pascal(c)));
            }
        }
        w.line(")");
        w.line("");
        for (c, payload) in cases {
            let cp = go_pascal(c);
            w.line(format!("// New{p}{cp} returns the `{c}` case of {p}."));
            match payload {
                None => {
                    w.open(format!("func New{p}{cp}() {p} {{"));
                    w.line(format!("return {p}{{Tag: {p}Tag{cp}}}"));
                    w.close("}");
                }
                Some(pt) => {
                    w.open(format!(
                        "func New{p}{cp}(payload {}) {p} {{",
                        go_ty(pt, "", 0)?
                    ));
                    w.line(format!("return {p}{{Tag: {p}Tag{cp}, {cp}: &payload}}"));
                    w.close("}");
                }
            }
            w.line("");
        }

        // encode
        let mut cx = Cx::new("return nil, err");
        let mut bw = W::new();
        bw.ind = 1;
        bw.open("switch v.Tag {");
        for (i, (c, payload)) in cases.iter().enumerate() {
            let cp = go_pascal(c);
            bw.ind -= 1;
            bw.line(format!("case {p}Tag{cp}:"));
            bw.ind += 1;
            match payload {
                None => bw.line(format!("out = EncodeCase(out, {i})")),
                Some(pt) => {
                    bw.open(format!("if v.{cp} == nil {{"));
                    bw.line(format!(
                        "return nil, errors.New(\"{p}: case {c} has a nil payload\")"
                    ));
                    bw.close("}");
                    bw.line(format!("out = EncodeCase(out, {i})"));
                    emit_encode_deref(&mut bw, &mut cx, pt, &format!("v.{cp}"))?;
                }
            }
        }
        bw.ind -= 1;
        bw.line("default:");
        bw.ind += 1;
        bw.line(format!(
            "return nil, fmt.Errorf(\"invalid {p} tag: %d\", v.Tag)"
        ));
        bw.close("}");
        let mut body = bw.buf;
        if cx.used_err {
            body = format!("\tvar err error\n{body}");
        }
        self.write_encode_helper(w, &p, body);

        // decode
        let mut cx = Cx::new("return");
        let mut bw = W::new();
        bw.ind = 1;
        bw.line("var c uint32");
        bw.line(format!("c, err = d.VariantCase({})", cases.len()));
        bw.open("if err != nil {");
        bw.line("return");
        bw.close("}");
        bw.line("v.Tag = int(c)");
        if cases.iter().any(|(_, p)| p.is_some()) {
            bw.open("switch c {");
            for (i, (c, payload)) in cases.iter().enumerate() {
                let Some(pt) = payload else { continue };
                bw.ind -= 1;
                bw.line(format!("case {i}:"));
                bw.ind += 1;
                let x = cx.fresh("x");
                bw.line(format!("var {x} {}", go_ty(pt, "", bw.ind)?));
                emit_decode(&mut bw, &mut cx, pt, &x)?;
                bw.line(format!("v.{} = &{x}", go_pascal(c)));
            }
            bw.close("}");
        }
        self.write_decode_helper(w, &p, &bw.buf);
        Ok(())
    }

    // -- function signatures ---------------------------------------------------

    /// "EchoEverything(e Everything) (Everything, error)" — shared by the
    /// Impl interface, the scaffolded stubs, and missing_impls output.
    fn method_sig(&self, f: &Func, qual: &str) -> Result<String> {
        let params = f
            .params
            .iter()
            .map(|(n, t)| Ok(format!("{} {}", go_param(n), go_ty(t, qual, 0)?)))
            .collect::<Result<Vec<_>>>()?
            .join(", ");
        let ret = match self.classify(f)?.value_ty() {
            Some(t) => format!("({}, error)", go_ty(t, qual, 0)?),
            None => "error".to_string(),
        };
        Ok(format!("{}({params}) {ret}", go_pascal(&f.wit_name)))
    }

    /// One doc line describing where a method's returned error goes.
    fn err_doc(&self, f: &Func) -> Result<&'static str> {
        Ok(match self.classify(f)? {
            Ret::ResStr { has_msg: true, .. } => {
                "// A non-nil error encodes as the WIT result err case (a normal status-0 reply)."
            }
            Ret::ResStr { has_msg: false, .. } => {
                "// A non-nil error encodes as the WIT result err case (no payload: the message is dropped)."
            }
            _ => "// A non-nil error is a function-level failure (status-1 reply).",
        })
    }

    // -- bindings.go -----------------------------------------------------------

    fn bindings_go(&self) -> Result<String> {
        let mut w = W::new();

        if self.need_result {
            w.line("// Result mirrors a WIT result<T, E> in value position: IsErr selects the");
            w.line("// populated side; sides with no payload use struct{}.");
            w.line("type Result[T any, E any] struct {");
            w.line("\tIsErr bool");
            w.line("\tOk    T");
            w.line("\tErr   E");
            w.line("}");
            w.line("");
        }

        for iface in self.m.exports.iter().chain(&self.m.imports) {
            for t in &iface.types {
                self.emit_named_ty(&mut w, iface, t)?;
            }
        }

        let export = &self.m.exports[0];
        w.line("// Impl is the application interface: one method per function exported by");
        w.line(format!(
            "// {}. impl.go implements it and registers the implementation",
            export.instance
        ));
        w.line("// via SetImpl from init().");
        w.open("type Impl interface {");
        for (i, f) in export.funcs.iter().enumerate() {
            if i > 0 {
                w.line("");
            }
            w.line(format!(
                "// {} handles {}#{}.",
                go_pascal(&f.wit_name),
                export.instance,
                f.wit_name
            ));
            w.line(self.err_doc(f)?);
            w.line(self.method_sig(f, "")?);
        }
        w.close("}");
        w.line("");
        w.line("var impl Impl");
        w.line("");
        w.line("// SetImpl registers the application implementation; the scaffolded impl.go");
        w.line("// calls it from init().");
        w.line("func SetImpl(i Impl) { impl = i }");
        w.line("");
        w.line("var errNoImpl = errors.New(\"no implementation registered: impl.go must call gen.SetImpl in init()\")");
        w.line("");

        for f in &export.funcs {
            self.emit_args_decoder(&mut w, f)?;
            self.emit_handler(&mut w, export, f)?;
        }

        if !export.funcs.is_empty() {
            w.open("func init() {");
            for f in &export.funcs {
                w.line(format!(
                    "handlers[\"{}#{}\"] = handle{}",
                    export.instance,
                    f.wit_name,
                    go_pascal(&f.wit_name)
                ));
            }
            w.close("}");
            w.line("");
        }

        let mut out = String::new();
        out.push_str(GENERATED_HEADER);
        out.push_str("\n//\n");
        out.push_str(&format!(
            "// Typed bindings for WIT package {}, world {}: native declarations for\n",
            self.m.package, self.m.world
        ));
        out.push_str("// every WIT type, straight-line WIRE codecs, the Impl interface the\n");
        out.push_str("// application implements (see impl.go), and the crab_invoke dispatch\n");
        out.push_str("// entries.\n");
        out.push_str("//\n");
        out.push_str("// Error semantics (WIRE.md): a method for a WIT function returning\n");
        out.push_str("// result<T, string> (or result with no err payload) maps a non-nil error\n");
        out.push_str("// to the WIRE result ERR CASE — a normal status-0 reply carrying an\n");
        out.push_str("// encoded result value. Every other method's non-nil error is a\n");
        out.push_str("// function-level failure: the runtime replies status 1 with\n");
        out.push_str("// \"<function>: <message>\".\n");
        out.push_str("package gen\n");
        // NB: imports_block is a substring scan that sees comments too: a
        // generated doc comment containing "fmt." or "errors." needlessly
        // forces the import (harmless) — it can over-include, never miss.
        out.push_str(&imports_block(&w.buf));
        out.push_str(&w.buf);
        Ok(trim_final(&out))
    }

    /// decode<Fn>Args: named results (typed params + err), straight-line
    /// Decoder calls, ALWAYS finishing with d.Finish("params").
    fn emit_args_decoder(&self, w: &mut W, f: &Func) -> Result<()> {
        let p = go_pascal(&f.wit_name);
        let mut sig_params = Vec::new();
        for (n, t) in &f.params {
            sig_params.push(format!("{} {}", go_param(n), go_ty(t, "", 0)?));
        }
        sig_params.push("err error".to_string());
        w.line(format!(
            "// decode{p}Args decodes the WIRE-encoded params of `{}`.",
            f.wit_name
        ));
        w.open(format!(
            "func decode{p}Args(d *Decoder) ({}) {{",
            sig_params.join(", ")
        ));
        let mut cx = Cx::new("return");
        for (n, t) in &f.params {
            let dest = go_param(n);
            emit_decode(w, &mut cx, t, &dest)?;
        }
        w.line("err = d.Finish(\"params\")");
        w.line("return");
        w.close("}");
        w.line("");
        Ok(())
    }

    fn emit_handler(&self, w: &mut W, iface: &Iface, f: &Func) -> Result<()> {
        let p = go_pascal(&f.wit_name);
        let params: Vec<String> = f.params.iter().map(|(n, _)| go_param(n)).collect();
        w.line(format!(
            "// handle{p} dispatches {}#{}; registered in init().",
            iface.instance, f.wit_name
        ));
        w.open(format!("func handle{p}(d *Decoder) ([]byte, error) {{"));
        w.open("if impl == nil {");
        w.line("return nil, errNoImpl");
        w.close("}");
        let mut lhs = params.clone();
        lhs.push("err".to_string());
        w.line(format!("{} := decode{p}Args(d)", lhs.join(", ")));
        w.open("if err != nil {");
        w.line("return nil, fmt.Errorf(\"bad params: %w\", err)");
        w.close("}");
        let call = format!("impl.{p}({})", params.join(", "));
        match self.classify(f)? {
            Ret::None => {
                w.open(format!("if err := {call}; err != nil {{"));
                w.line("return nil, err");
                w.close("}");
                w.line("return nil, nil");
            }
            Ret::Plain(t) => {
                w.line(format!("r, err := {call}"));
                w.open("if err != nil {");
                w.line("return nil, err");
                w.close("}");
                w.line("var out []byte");
                let mut cx = Cx::new("return nil, err");
                emit_encode(w, &mut cx, t, "r")?;
                w.line("return out, nil");
            }
            Ret::ResStr { ok, has_msg } => {
                match ok {
                    Some(_) => w.line(format!("r, err := {call}")),
                    None => w.line(format!("err = {call}")),
                }
                w.line("var out []byte");
                w.open("if err != nil {");
                w.line("out = EncodeResultTag(out, true)");
                if has_msg {
                    w.line("out = EncodeString(out, err.Error())");
                } else {
                    w.line("// the WIT err side has no payload: the message is dropped");
                }
                w.line("return out, nil");
                w.close("}");
                w.line("out = EncodeResultTag(out, false)");
                if let Some(okt) = ok {
                    let mut cx = Cx::new("return nil, err");
                    emit_encode(w, &mut cx, okt, "r")?;
                }
                w.line("return out, nil");
            }
            Ret::ResTyped(t) => {
                w.line(format!("r, err := {call}"));
                w.open("if err != nil {");
                w.line("return nil, err");
                w.close("}");
                w.line("var out []byte");
                let mut cx = Cx::new("return nil, err");
                emit_encode(w, &mut cx, t, "r")?;
                w.line("return out, nil");
            }
        }
        w.close("}");
        w.line("");
        Ok(())
    }

    // -- imports.go (mesh wrappers) ---------------------------------------------

    fn imports_go(&self) -> Result<String> {
        let mut w = W::new();
        for iface in &self.m.imports {
            let ip = go_pascal(iface_short(&iface.instance));
            for f in &iface.funcs {
                self.emit_mesh_wrapper(&mut w, iface, &ip, f)?;
            }
        }
        let mut out = String::new();
        out.push_str(GENERATED_HEADER);
        out.push_str("\n//\n");
        out.push_str("// Typed mesh wrappers for the world's imported interfaces: each function\n");
        out.push_str(
            "// becomes a package-level wrapper that WIRE-encodes its params, calls the\n",
        );
        out.push_str("// named workload through the host mesh (crabcraft.call import), and\n");
        out.push_str("// decodes the reply. The caller names the target deployment — crabgen\n");
        out.push_str("// never bakes one in; placement is the host's problem.\n");
        out.push_str("package gen\n");
        // NB: imports_block is a substring scan that sees comments too: a
        // generated doc comment containing "fmt." or "errors." needlessly
        // forces the import (harmless) — it can over-include, never miss.
        out.push_str(&imports_block(&w.buf));
        out.push_str(&w.buf);
        Ok(trim_final(&out))
    }

    fn emit_mesh_wrapper(&self, w: &mut W, iface: &Iface, ip: &str, f: &Func) -> Result<()> {
        let name = format!("{ip}{}", go_pascal(&f.wit_name));
        let addr = format!("{}#{}", iface.instance, f.wit_name);
        let ret = self.classify(f)?;
        let mut sig_params = vec!["workload string".to_string()];
        for (n, t) in &f.params {
            sig_params.push(format!("{} {}", go_param(n), go_ty(t, "", 0)?));
        }
        let sig_ret = match ret.value_ty() {
            Some(t) => format!("(r {}, err error)", go_ty(t, "", 0)?),
            None => "(err error)".to_string(),
        };
        w.line(format!("// {name} calls {addr} on the workload named"));
        w.line("// `workload` through the host mesh. The returned error covers transport");
        let res_note = match ret {
            Ret::ResStr { .. } => {
                "// failures, remote status-1 failures, AND the WIT result err case."
            }
            _ => "// failures and remote status-1 failures.",
        };
        w.line(res_note);
        w.open(format!(
            "func {name}({}) {sig_ret} {{",
            sig_params.join(", ")
        ));
        // encode params
        let call_params = if f.params.is_empty() {
            "nil".to_string()
        } else {
            w.line("var out []byte");
            let mut cx = Cx::new("return");
            for (n, t) in &f.params {
                emit_encode(w, &mut cx, t, &go_param(n))?;
            }
            "out".to_string()
        };
        w.line("var body []byte");
        w.line(format!(
            "body, err = MeshCall(workload, \"{addr}\", {call_params})"
        ));
        w.open("if err != nil {");
        w.line("return");
        w.close("}");
        w.line("d := NewDecoder(body)");
        match ret {
            Ret::None => {
                w.line("err = d.Finish(\"reply\")");
                w.line("return");
            }
            Ret::Plain(t) => {
                let mut cx = Cx::new("return");
                emit_decode(w, &mut cx, t, "r")?;
                w.line("err = d.Finish(\"reply\")");
                w.line("return");
            }
            Ret::ResTyped(t) => {
                let mut cx = Cx::new("return");
                emit_decode(w, &mut cx, t, "r")?;
                w.line("err = d.Finish(\"reply\")");
                w.line("return");
            }
            Ret::ResStr { ok, has_msg } => {
                let mut cx = Cx::new("return");
                w.line("var isErr bool");
                w.line("isErr, err = d.ResultTag()");
                w.open("if err != nil {");
                w.line("return");
                w.close("}");
                w.open("if isErr {");
                if has_msg {
                    w.line("var msg string");
                    w.line("msg, err = d.String()");
                    w.open("if err != nil {");
                    w.line("return");
                    w.close("}");
                    w.open("if err = d.Finish(\"reply\"); err != nil {");
                    w.line("return");
                    w.close("}");
                    w.line("err = errors.New(msg)");
                } else {
                    w.open("if err = d.Finish(\"reply\"); err != nil {");
                    w.line("return");
                    w.close("}");
                    w.line(format!(
                        "err = errors.New(\"{}: err result (no payload)\")",
                        f.wit_name
                    ));
                }
                w.line("return");
                w.close("}");
                if let Some(okt) = ok {
                    emit_decode(w, &mut cx, okt, "r")?;
                }
                w.line("err = d.Finish(\"reply\")");
                w.line("return");
            }
        }
        w.close("}");
        w.line("");
        Ok(())
    }

    // -- scaffold files ----------------------------------------------------------

    fn impl_go(&self) -> Result<String> {
        let export = &self.m.exports[0];
        let mut w = W::new();
        w.line("// impl.go — the application half of this guest: implement gen.Impl here.");
        w.line("// crabgen scaffolds this file ONCE and never overwrites it; `crabgen regen`");
        w.line("// prints any missing method signatures instead of editing it.");
        w.line("package main");
        w.line("");
        if export.funcs.is_empty() {
            w.line(format!("import \"crabcraft.local/{}/gen\"", self.project));
        } else {
            w.line("import (");
            w.line("\t\"fmt\"");
            w.line("");
            w.line(format!("\t\"crabcraft.local/{}/gen\"", self.project));
            w.line(")");
        }
        w.line("");
        w.line("// App implements gen.Impl: one method per function exported by");
        w.line(format!("// {}.", export.instance));
        w.line("type App struct{}");
        w.line("");
        for f in &export.funcs {
            w.line(format!(
                "// {} handles {}#{}.",
                go_pascal(&f.wit_name),
                export.instance,
                f.wit_name
            ));
            w.line(self.err_doc(f)?);
            w.open(format!("func (App) {} {{", self.method_sig(f, "gen.")?));
            let unimpl = format!("fmt.Errorf(\"unimplemented: {}\")", f.wit_name);
            match self.classify(f)?.value_ty() {
                Some(t) => w.line(format!("return {}, {unimpl}", self.zero(t, "gen.", 1)?)),
                None => w.line(format!("return {unimpl}")),
            }
            w.close("}");
            w.line("");
        }
        w.line("func init() { gen.SetImpl(App{}) }");
        w.line("");
        w.line("// main never runs: the module builds as a wasip1 reactor (the host calls");
        w.line("// _initialize once, then crab_invoke per request).");
        w.line("func main() {}");
        Ok(trim_final(&w.buf))
    }
}

/// "crab:full/telemetry@0.1.0" → "telemetry"
fn iface_short(instance: &str) -> &str {
    let after = instance.rsplit('/').next().unwrap_or(instance);
    after.split('@').next().unwrap_or(after)
}

/// Build the import block for a generated gen file by scanning the body for
/// stdlib usage (the only candidates are errors and fmt).
fn imports_block(body: &str) -> String {
    let errors = body.contains("errors.");
    let fmt = body.contains("fmt.");
    match (errors, fmt) {
        (true, true) => "\nimport (\n\t\"errors\"\n\t\"fmt\"\n)\n\n".to_string(),
        (true, false) => "\nimport \"errors\"\n\n".to_string(),
        (false, true) => "\nimport \"fmt\"\n\n".to_string(),
        (false, false) => "\n".to_string(),
    }
}

/// Exactly one trailing newline (gofmt).
fn trim_final(s: &str) -> String {
    format!("{}\n", s.trim_end())
}

fn schema_go() -> String {
    format!(
        r#"{GENERATED_HEADER}
//
// schema.go serves gen/schema.json (the resolved-WIT JSON written by the
// crabgen driver) through the runtime's crab_schema export.
package gen

import _ "embed"

//go:embed schema.json
var schemaJSON string

func init() {{ Schema = schemaJSON }}
"#
    )
}

fn go_mod(name: &str) -> String {
    format!(
        "// crabcraft guest module (Go lane), scaffolded by crabgen.\nmodule crabcraft.local/{name}\n\ngo 1.24\n"
    )
}

fn build_sh(name: &str) -> String {
    format!(
        r#"#!/usr/bin/env bash
# Build the {name} reactor module (scaffolded by crabgen; edit freely — this
# file is written once and never overwritten).
#
# -buildmode=c-shared is what makes this a REACTOR: the wasm exports
# `_initialize` (run once by the host) and has no `_start` requirement at
# invoke time. -scheduler=none / -no-debug keep the binary small.
set -euo pipefail
cd "$(dirname "$0")"

nix shell nixpkgs#tinygo --command tinygo build -o ../../modules/{name}.wasm \
  -target=wasip1 -buildmode=c-shared -scheduler=none -no-debug .

# SIMD tripwire: the wasmcraft engine refuses 0xfd-prefixed (SIMD) opcodes.
# wasm-objdump prints opcode bytes as "fd 0c" (no 0x prefix) and SIMD
# mnemonics as v128.*/i8x16.*/... after the "|" column; anchor the mnemonic
# check to that column so a symbol name containing e.g. "i32x4" can't
# false-positive. The byte check can in rare cases match a wrapped non-SIMD
# instruction's continuation byte (loud + debuggable, accepted).
disasm="$(nix shell nixpkgs#wabt --command wasm-objdump -d ../../modules/{name}.wasm)"
if grep -qE '\| +(v128|i8x16|i16x8|i32x4|i64x2|f32x4|f64x2|f16x8)\.' <<<"$disasm" ||
   grep -qE '^ *[0-9a-f]+: fd' <<<"$disasm"; then
  echo 'FATAL: SIMD opcodes in output wasm' >&2
  exit 1
fi

ls -la ../../modules/{name}.wasm
"#
    )
}

fn readme(name: &str, m: &Module) -> String {
    let instance = &m.exports[0].instance;
    format!(
        r#"# {name} — crabcraft guest (Go lane)

<!-- generated by crabgen — edits will be overwritten on regen -->

Generated by crabgen. `{name}.wit` is the source of truth; `gen/` and this
README are GENERATED — never edit them, crabgen rewrites them wholesale on
every regen. Your code lives in `impl.go` (crabgen never touches it).

## Build

    ./build.sh

TinyGo (via nix) builds a wasip1 reactor at `../../modules/{name}.wasm`,
then the script fails hard if any SIMD (0xfd) opcodes snuck in — the
wasmcraft engine refuses them. Host-side unit tests run with plain go:
`nix shell nixpkgs#go --command go test ./...`.

## Deploy

Add a manifest and apply it in-game with `crb apply` (exported interface:
`{instance}`):

```yaml
name: {name}
wasm: <URL serving modules/{name}.wasm>
kind: reactor
schema: <URL serving the resolved-WIT JSON>   # serve a copy of gen/schema.json
```

## Maintenance loop

1. Edit `{name}.wit`.
2. `crabgen regen guest/{name}` — rewrites `gen/` and prints typed
   signatures for any functions missing from `impl.go`.
3. Paste the stubs into `impl.go` and implement them.
4. `./build.sh`, redeploy, invoke.

`crabgen check` (run it in CI/pre-commit) fails while `gen/` is stale.

## WIT versioning

Backwards-compatible evolution: add new functions freely, and add new
inputs as `option<T>` (old callers simply omit them). Anything else is a
breaking change: bump the package version (`@0.1.0` → `@0.2.0`) and the
daemon serves both versions side by side.
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pascal_titles_each_dash_segment() {
        assert_eq!(go_pascal("echo-everything"), "EchoEverything");
        assert_eq!(go_pascal("a-u8"), "AU8");
        assert_eq!(go_pascal("hello-go"), "HelloGo");
        assert_eq!(go_pascal("x"), "X");
    }

    #[test]
    fn params_are_lower_camel_and_mangled() {
        assert_eq!(go_param("a-bool"), "aBool");
        assert_eq!(go_param("num"), "num");
        assert_eq!(go_param("type"), "type_"); // Go keyword
        assert_eq!(go_param("len"), "len_"); // predeclared
        assert_eq!(go_param("err"), "err_"); // generated local
        assert_eq!(go_param("is-err"), "isErr_"); // mesh-wrapper local
        assert_eq!(go_param("x0"), "x0_"); // temp-shaped
        assert_eq!(go_param("xs"), "xs"); // not temp-shaped
                                          // codec-helper locals never share a scope with params: no mangling
        assert_eq!(go_param("c"), "c");
        assert_eq!(go_param("v"), "v");
        assert_eq!(go_param("bits"), "bits");
    }

    #[test]
    fn field_alignment_matches_gofmt_sections() {
        // verified against gofmt: a multiline field ends its section and
        // counts toward its width; the next field starts a fresh section.
        let fields = vec![
            ("X".to_string(), "bool".to_string()),
            (
                "VeryLongTupleFieldName".to_string(),
                "struct {\n\t\tF0 uint8\n\t}".to_string(),
            ),
            ("Y".to_string(), "bool".to_string()),
        ];
        let got = align_fields(&fields, 1);
        assert_eq!(
            got,
            "\tX                      bool\n\
             \tVeryLongTupleFieldName struct {\n\t\tF0 uint8\n\t}\n\
             \tY bool\n"
        );
    }

    #[test]
    fn iface_short_strips_namespace_and_version() {
        assert_eq!(iface_short("crab:full/telemetry@0.1.0"), "telemetry");
        assert_eq!(iface_short("crab:full/kitchen"), "kitchen");
    }

    /// Top-level identifiers declared by a Go source file: `func Name(`
    /// (methods and init skipped), `type|var|const Name`, and the names
    /// inside `var (` / `const (` groups. Good enough for our templates —
    /// no generics, no multi-name single-line declarations.
    fn go_top_level_idents(src: &str) -> Vec<String> {
        fn first_ident(s: &str) -> Option<String> {
            let name: String = s
                .chars()
                .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
                .collect();
            (!name.is_empty()).then_some(name)
        }
        let mut out = Vec::new();
        let mut in_group = false;
        for line in src.lines() {
            if in_group {
                let t = line.trim();
                if t == ")" {
                    in_group = false;
                } else if !t.is_empty() && !t.starts_with("//") {
                    out.extend(first_ident(t));
                }
                continue;
            }
            if let Some(rest) = line.strip_prefix("func ") {
                if !rest.starts_with('(') {
                    // a plain function; methods (`func (recv)`) aren't pkg idents
                    if let Some(name) = first_ident(rest) {
                        if name != "init" {
                            out.push(name);
                        }
                    }
                }
            } else if let Some(rest) = ["type ", "var ", "const "]
                .iter()
                .find_map(|kw| line.strip_prefix(kw))
            {
                if rest.starts_with('(') {
                    in_group = true;
                } else {
                    out.extend(first_ident(rest));
                }
            }
        }
        out
    }

    #[test]
    fn template_identifiers_are_all_reserved() {
        // Guards silent drift: adding a top-level name to a template without
        // also reserving it would let WIT names collide with it undetected.
        for (file, src) in [
            ("runtime.go", RUNTIME_GO),
            ("runtime_test.go", RUNTIME_TEST_GO),
            ("mesh.go", MESH_GO),
            ("mesh_wasm.go", MESH_WASM_GO),
            ("mesh_test.go", MESH_TEST_GO),
        ] {
            let idents = go_top_level_idents(src);
            assert!(
                !idents.is_empty(),
                "{file}: the ident scan found nothing — parser broken?"
            );
            for ident in idents {
                assert!(
                    RESERVED.contains(&ident.as_str()),
                    "{file} declares top-level `{ident}` but RESERVED doesn't list it; \
                     add it so WIT-name collisions stay detectable"
                );
            }
        }
    }
}
