//! Shared emission plumbing used by every language backend (Go and Rust
//! today; C++/TS later). Only the byte-identical helpers live here —
//! casing rules, RESERVED tables and the Ret classification stay
//! per-backend, where the language differences are.

use std::path::Path;

use anyhow::{anyhow, Result};

pub const GENERATED_HEADER: &str = "// Code generated by crabgen. DO NOT EDIT.";

/// Line writer with a per-backend indent unit ("\t" for the Go lane —
/// gofmt's — four spaces for Rust). `line` may carry embedded newlines
/// (multiline expressions render their own inner indentation).
pub struct W {
    pub buf: String,
    pub ind: usize,
    unit: &'static str,
}

impl W {
    /// Tab-indented writer (Go).
    pub fn tabs() -> Self {
        Self::with_unit("\t")
    }

    /// Four-space-indented writer (Rust).
    pub fn spaces4() -> Self {
        Self::with_unit("    ")
    }

    /// Two-space-indented writer (C++ — the templates/cpp house style).
    pub fn spaces2() -> Self {
        Self::with_unit("  ")
    }

    fn with_unit(unit: &'static str) -> Self {
        W {
            buf: String::new(),
            ind: 0,
            unit,
        }
    }

    pub fn line(&mut self, s: impl AsRef<str>) {
        let s = s.as_ref();
        if !s.is_empty() {
            for _ in 0..self.ind {
                self.buf.push_str(self.unit);
            }
            self.buf.push_str(s);
        }
        self.buf.push('\n');
    }

    pub fn open(&mut self, s: impl AsRef<str>) {
        self.line(s);
        self.ind += 1;
    }

    pub fn close(&mut self, s: impl AsRef<str>) {
        self.ind -= 1;
        self.line(s);
    }
}

/// Four-space indentation for free-standing expression builders (Rust lane).
pub fn pad(ind: usize) -> String {
    "    ".repeat(ind)
}

/// Exactly one trailing newline (gofmt's rule; right for Rust too).
pub fn trim_final(s: &str) -> String {
    format!("{}\n", s.trim_end())
}

/// "crab:full/telemetry@0.1.0" → "telemetry"
pub fn iface_short(instance: &str) -> &str {
    let after = instance.rsplit('/').next().unwrap_or(instance);
    after.split('@').next().unwrap_or(after)
}

/// The project name is the directory name (`guest/<name>` invariant).
pub fn project_name(dir: &Path) -> Result<String> {
    dir.file_name()
        .map(|n| n.to_string_lossy().to_string())
        .ok_or_else(|| anyhow!("project dir {} has no name", dir.display()))
}

/// Matches a generated temp-name pattern: any `prefix` followed by only
/// digits (x0, n1, isErr2, ...). Each backend passes the prefixes its
/// emitter actually generates.
pub fn is_temp_shaped(s: &str, prefixes: &[&str]) -> bool {
    for prefix in prefixes {
        if let Some(rest) = s.strip_prefix(prefix) {
            if !rest.is_empty() && rest.bytes().all(|b| b.is_ascii_digit()) {
                return true;
            }
        }
    }
    false
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn writer_indents_with_its_unit() {
        let mut w = W::tabs();
        w.open("a {");
        w.line("b");
        w.close("}");
        assert_eq!(w.buf, "a {\n\tb\n}\n");

        let mut w = W::spaces4();
        w.open("a {");
        w.line("b");
        w.line(""); // empty lines carry no indentation
        w.close("}");
        assert_eq!(w.buf, "a {\n    b\n\n}\n");
    }

    #[test]
    fn iface_short_strips_namespace_and_version() {
        assert_eq!(iface_short("crab:full/telemetry@0.1.0"), "telemetry");
        assert_eq!(iface_short("crab:full/kitchen"), "kitchen");
    }

    #[test]
    fn temp_shapes_are_prefix_plus_digits() {
        assert!(is_temp_shaped("x0", &["x"]));
        assert!(!is_temp_shaped("x", &["x"]));
        assert!(!is_temp_shaped("xs", &["x"]));
        assert!(is_temp_shaped("isErr12", &["x", "isErr"]));
        assert!(!is_temp_shaped("isErr", &["x", "isErr"]));
    }
}
