// crabcraft sqlite-c module: implements crab:sqlite/db@0.1.0 (wit/sqlite.wit)
// as a wasm32-wasip1 REACTOR in plain C — the C lane of the "any language,
// our ABI" contract (see docs/WIRE.md sections 1-2). Built with
//   zig cc -target wasm32-wasi -mexec-model=reactor ...   (see build.sh)
//
// Persistence: the host mounts the workload's volume as the WASI cwd, so the
// database file "crab.db" (opened lazily on first exec, kept open in a static
// handle) lives on the volume and survives instance restarts.
//
// exec(sql: string) -> result<string, string>
//   ok  = a compact JSON string {"columns":[...],"rows":[[...],...],"changes":n}
//   err = sqlite3_errmsg text (WIT-level result err case, NOT the ABI error
//         status — that is reserved for protocol problems like unknown
//         function or malformed params).
//
// JSON encoding choices (documented per the spec):
//   - INTEGER  -> JSON number (%lld)
//   - FLOAT    -> JSON number (%.17g); NaN/Inf -> null (not representable)
//   - TEXT     -> JSON string, escaping `"` `\` and control chars (<0x20)
//                 as \" \\ \n \r \t or \u00XX; bytes >=0x20 pass through
//                 (SQLite TEXT is UTF-8)
//   - NULL     -> null
//   - BLOB     -> JSON string of lowercase hex digits (e.g. x'CAFE' -> "cafe")
//   - "changes" = sqlite3_changes() after the statement completes (meaningful
//     for INSERT/UPDATE/DELETE; stale/0 for SELECT and DDL)
//   - ONE statement per exec: trailing non-whitespace after the first
//     statement is an error ("only one statement per exec").
//
// Reply layering (the part that is easy to get wrong — mirrors the Rust SDK
// abi.rs and guest/hello-go/main.go): LENBUF = [u32 LE len][payload], and
//   payload = [ABI status 0][encoded result<string,string>]
//           = [0][0][uleb len][json]    on SQL success
//           = [0][1][uleb len][errmsg]  on SQL error (still ABI-ok!)
//   payload = [1][uleb len][message]    only for protocol errors
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <math.h>
#include "sqlite3.h"
#include "schema_json.h" // generated by build.sh (xxd -i schema.json):
                         //   unsigned char schema_json[]; unsigned int schema_json_len;

#define EXPORT(n) __attribute__((export_name(n)))

static const char *FN_EXEC = "crab:sqlite/db@0.1.0#exec";
static const char *DB_FILE = "crab.db";

// ---------------------------------------------------------------------------
// growable byte buffer
// ---------------------------------------------------------------------------
typedef struct { char *p; size_t len, cap; } buf;

static void breset(buf *b) { b->len = 0; }
static void bput(buf *b, const void *s, size_t n) {
  if (b->len + n > b->cap) {
    size_t cap = b->cap ? b->cap : 256;
    while (cap < b->len + n) cap *= 2;
    b->p = realloc(b->p, cap);
    b->cap = cap;
  }
  memcpy(b->p + b->len, s, n);
  b->len += n;
}
static void bputc(buf *b, char c) { bput(b, &c, 1); }
static void bputs(buf *b, const char *s) { bput(b, s, strlen(s)); }
static void bputf(buf *b, const char *fmt, ...) { // small formatted appends only
  char tmp[64];
  __builtin_va_list ap; __builtin_va_start(ap, fmt);
  int n = vsnprintf(tmp, sizeof tmp, fmt, ap);
  __builtin_va_end(ap);
  if (n > 0) bput(b, tmp, (size_t)n < sizeof tmp ? (size_t)n : sizeof tmp - 1);
}

// ---------------------------------------------------------------------------
// WIRE.md section 1 codec: uleb + string
// ---------------------------------------------------------------------------
static void uleb_put(buf *b, unsigned long long v) {
  do {
    unsigned char byte = v & 0x7f;
    v >>= 7;
    if (v) byte |= 0x80;
    bput(b, &byte, 1);
  } while (v);
}

// decode uleb capped at 32 bits; returns 0 ok, -1 error
static int uleb_get32(const unsigned char *p, size_t len, size_t *pos, unsigned *out) {
  unsigned result = 0;
  for (unsigned i = 0; i < 5; i++) { // ceil(32/7) = 5 bytes max
    if (*pos >= len) return -1;
    unsigned char byte = p[(*pos)++];
    unsigned payload = byte & 0x7f;
    if (i == 4 && (payload >> 4) != 0) return -1; // overflow past 32 bits
    result |= payload << (7 * i);
    if (!(byte & 0x80)) { *out = result; return 0; }
  }
  return -1; // too long
}

// ---------------------------------------------------------------------------
// reply LENBUF (valid until the next crab_invoke/crab_schema, host copies)
// ---------------------------------------------------------------------------
static buf REPLY;

static void *lenbuf(const void *payload, size_t n) {
  breset(&REPLY);
  unsigned char hdr[4] = { n & 0xff, (n >> 8) & 0xff, (n >> 16) & 0xff, (n >> 24) & 0xff };
  bput(&REPLY, hdr, 4);
  bput(&REPLY, payload, n);
  return REPLY.p;
}

// protocol-level error: [1][uleb len][msg]
static void *reply_abi_err(const char *msg) {
  buf b = {0};
  bputc(&b, 1);
  uleb_put(&b, strlen(msg));
  bputs(&b, msg);
  void *r = lenbuf(b.p, b.len);
  free(b.p);
  return r;
}

// ABI ok wrapping the WIT result<string,string>: [0][case][uleb len][s]
static void *reply_result(int err_case, const char *s, size_t n) {
  buf b = {0};
  bputc(&b, 0);                 // ABI status: ok
  bputc(&b, err_case ? 1 : 0);  // result<_,_> discriminant
  uleb_put(&b, n);
  bput(&b, s, n);
  void *r = lenbuf(b.p, b.len);
  free(b.p);
  return r;
}

// ---------------------------------------------------------------------------
// JSON helpers
// ---------------------------------------------------------------------------
static void json_string(buf *b, const char *s, size_t n) {
  bputc(b, '"');
  for (size_t i = 0; i < n; i++) {
    unsigned char c = (unsigned char)s[i];
    switch (c) {
      case '"':  bputs(b, "\\\""); break;
      case '\\': bputs(b, "\\\\"); break;
      case '\n': bputs(b, "\\n");  break;
      case '\r': bputs(b, "\\r");  break;
      case '\t': bputs(b, "\\t");  break;
      default:
        if (c < 0x20) bputf(b, "\\u%04x", c);
        else bputc(b, (char)c);
    }
  }
  bputc(b, '"');
}

// ---------------------------------------------------------------------------
// SQLite: lazy static handle on crab.db in the WASI cwd (= the volume)
// ---------------------------------------------------------------------------
static sqlite3 *DB = 0;

static const char *db_open(void) { // returns error message or NULL
  if (DB) return 0;
  if (sqlite3_open(DB_FILE, &DB) != SQLITE_OK) {
    static char err[256];
    snprintf(err, sizeof err, "cannot open %s: %s", DB_FILE,
             DB ? sqlite3_errmsg(DB) : "out of memory");
    if (DB) { sqlite3_close(DB); DB = 0; }
    return err;
  }
  return 0;
}

// run one SQL statement; on success fill `out` with the JSON doc and return 0,
// else put sqlite's message in `out` and return 1. (caller frees out->p never:
// out is a static buffer reset per call)
static int run_sql(const char *sql, size_t sql_len, buf *out) {
  breset(out);

  const char *err = db_open();
  if (err) { bputs(out, err); return 1; }

  sqlite3_stmt *stmt = 0;
  const char *tail = 0;
  if (sqlite3_prepare_v2(DB, sql, (int)sql_len, &stmt, &tail) != SQLITE_OK) {
    bputs(out, sqlite3_errmsg(DB));
    return 1;
  }
  // one statement per exec: anything but whitespace/';' after it is an error
  for (const char *t = tail; t && t < sql + sql_len; t++) {
    if (*t != ' ' && *t != '\t' && *t != '\n' && *t != '\r' && *t != ';' && *t != 0) {
      sqlite3_finalize(stmt);
      bputs(out, "only one statement per exec");
      return 1;
    }
  }
  if (!stmt) { // pure whitespace/comment "statement"
    bputs(out, "{\"columns\":[],\"rows\":[],\"changes\":0}");
    return 0;
  }

  int ncol = sqlite3_column_count(stmt);
  bputs(out, "{\"columns\":[");
  for (int i = 0; i < ncol; i++) {
    if (i) bputc(out, ',');
    const char *name = sqlite3_column_name(stmt, i);
    json_string(out, name ? name : "", name ? strlen(name) : 0);
  }
  bputs(out, "],\"rows\":[");

  int rc, nrow = 0;
  while ((rc = sqlite3_step(stmt)) == SQLITE_ROW) {
    if (nrow++) bputc(out, ',');
    bputc(out, '[');
    for (int i = 0; i < ncol; i++) {
      if (i) bputc(out, ',');
      switch (sqlite3_column_type(stmt, i)) {
        case SQLITE_INTEGER:
          bputf(out, "%lld", (long long)sqlite3_column_int64(stmt, i));
          break;
        case SQLITE_FLOAT: {
          double d = sqlite3_column_double(stmt, i);
          if (isnan(d) || isinf(d)) bputs(out, "null"); // not valid JSON numbers
          else bputf(out, "%.17g", d);
          break;
        }
        case SQLITE_NULL:
          bputs(out, "null");
          break;
        case SQLITE_BLOB: { // lowercase hex string
          const unsigned char *p = sqlite3_column_blob(stmt, i);
          int n = sqlite3_column_bytes(stmt, i);
          bputc(out, '"');
          for (int j = 0; j < n; j++) bputf(out, "%02x", p[j]);
          bputc(out, '"');
          break;
        }
        default: { // SQLITE_TEXT
          const unsigned char *p = sqlite3_column_text(stmt, i);
          int n = sqlite3_column_bytes(stmt, i);
          json_string(out, (const char *)p, (size_t)n);
        }
      }
    }
    bputc(out, ']');
  }

  if (rc != SQLITE_DONE) {
    breset(out);
    bputs(out, sqlite3_errmsg(DB));
    sqlite3_finalize(stmt);
    return 1;
  }
  sqlite3_finalize(stmt);

  bputf(out, "],\"changes\":%d}", sqlite3_changes(DB));
  return 0;
}

// ---------------------------------------------------------------------------
// WIRE.md section 2: guest ABI exports
// ---------------------------------------------------------------------------
EXPORT("crab_alloc") void *crab_alloc(int len) {
  return malloc(len < 1 ? 1 : len);
}

EXPORT("crab_schema") void *crab_schema(void) {
  return lenbuf(schema_json, schema_json_len);
}

EXPORT("crab_invoke") void *crab_invoke(const char *name_ptr, int name_len,
                                        const unsigned char *arg_ptr, int arg_len) {
  if ((size_t)name_len != strlen(FN_EXEC) || memcmp(name_ptr, FN_EXEC, name_len) != 0) {
    static char msg[256];
    int n = name_len < 200 ? name_len : 200;
    snprintf(msg, sizeof msg, "unknown function: %.*s", n, name_ptr);
    return reply_abi_err(msg);
  }

  // params: one WIRE.md string = uleb(len) + utf8 sql
  size_t pos = 0;
  unsigned sql_len = 0;
  if (uleb_get32(arg_ptr, (size_t)arg_len, &pos, &sql_len) != 0)
    return reply_abi_err("bad params: invalid string length");
  if (pos + sql_len > (size_t)arg_len)
    return reply_abi_err("bad params: unexpected end of buffer");
  if (pos + sql_len != (size_t)arg_len)
    return reply_abi_err("bad params: trailing bytes after params");

  static buf out; // JSON document or sqlite error message
  int is_err = run_sql((const char *)arg_ptr + pos, sql_len, &out);
  return reply_result(is_err, out.p ? out.p : "", out.len);
}
