// Code generated by crabgen. DO NOT EDIT.
//
// full: crabcraft guest module implementing crab:full/kitchen@0.1.0
// (see full.wit). A wasm32-wasip1 reactor cdylib: this file only wires the
// generated bindings (src/gen/) and the application (src/app.rs) into the
// WIRE.md section 2 ABI. Regenerated on every `crabgen regen` — your code
// belongs in src/app.rs.

mod app;
mod gen;

crab_sdk::export_abi!(schema: gen::SCHEMA, init: gen::setup);
