// Code generated by crabgen. DO NOT EDIT.
//
// Entry file: asc only turns exports of the ENTRY file into wasm exports,
// so the WIRE ABI is re-exported here. The register() call below is a
// top-level statement: it compiles into the module start function, which
// build.sh exports as the reactor's `_initialize` (--exportStart) — the
// host calls it once before invoking.
export { crab_alloc, crab_schema, crab_invoke } from "./gen/runtime";
import { register } from "./gen/bindings";
register();
